class Listas:
    stands = [
        'anubis',
        'moody blues',
        'Spice girl',
        'Tusk',
        'Pocoloco',
        'seth',
        'mettalica',
        'Cinderella',
        'judgement',
        'cath the rainbow',
        'doppios king Crimson',
        'beach boy',
        'harvest',
        'Highway star',
        'Tender machine',
        'man in the mirror',
        'Hermit purple',
        'Golden experience',
        'Sticky Fingers',
        'Greatful death',
        'Enigma',
        'Marelline Manzon',
        'Stone free',
        'Kiss',
        'Foo Fighters',
        'Heavens Doors',
        'Atum',
        'Aerosmith',
        'Silver Chariot',
        'Magicians Red',
        'Crazy Diamond',
        '33',
        'Ticker to Ride',
        'Soft N Wet',
        'Killer queen',
        'The World',
        'White snake',
        'Scary Monster',
        'C-Moon',
        'High Priestess',
        'Yellow Temperance',
        'Cream',
        'Weather Report',
        'Death 13',
        'The Devil',
        'The Great Fly']

    clima = [
        'nada',
        'tormenta leve',
        'Tormenta media',
        'Tormenta fuerte',
        'Tormenta extrema',
        'Salvado por esta vez']
    
    mapa = [
        'Minecraft',
        'Mundo de hielo',
        'Mundo Club',
        'Third Ninja War',
        'Mundo Fangirls',
        'Cielo',
        'Bosque (Nevado)',
        'Ciudad',
        'Pueblo',
        'Bioma caca',
        'Bosque (Normal)']

    demons = [
        'Chainsaw Demon',
        'Denji',
        'Power',
        'Beam',
        'Spider Demon',
        'Control Demon',
        'Demonio Pistola',
        'Katana Demon',
        'Demonio Maldición',
        'Demonio Flecha',
        'Demonio de la Oscuridad',
        'Demonio Infierno',
        'Demonio de la Violencia',
        'Demonio Bomba',
        'Demonio Ángel',
        'Demonio Zombie',
        'Demonio Torbellino',
        'Demonio del Futuro',
        'Demonio Fantasma',
        'Beelzebub',
        'Lucifer DC',
        'Lucifer Morningstar',
        'Rin Okumura',
        'Ram',
        'Rem',
        'Suika Ibuki',
        'Belfegor',
        'Agagliereth',
        'Agares',
        'Ahazu',
        'Amazarac',
        'Bill Cipher',
        'Hellboy',
        'Raven',
        'Demonio Radio',
        'Nine Tail Fox',
        'El Rey Demonio (NNT)',
        'Muzan',
        'Kiss Shot Acerola Orion Heart Underblade',
        'Merumeru',
        'Traigon',
        'Demonio Pulpo',
        'Demonio muñeca']